// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbS1uB7_wsOcUBQagQrnZYzVWRPQwUa1A',
    appId: '1:161385731577:web:ab7026f60e2f6a33dd5928',
    messagingSenderId: '161385731577',
    projectId: 'huong-nghiep',
    authDomain: 'huong-nghiep.firebaseapp.com',
    storageBucket: 'huong-nghiep.appspot.com',
    measurementId: 'G-FPDZS4DKRL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8ejG7Hm327HEfqRdLPzh5dke3Vc_TOLA',
    appId: '1:161385731577:android:a3f1cbc62a42cee7dd5928',
    messagingSenderId: '161385731577',
    projectId: 'huong-nghiep',
    storageBucket: 'huong-nghiep.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKN1dwFciR7DEOzgJQCGzUBZ6ft7lIaxQ',
    appId: '1:161385731577:ios:8be4eff2f6e715fbdd5928',
    messagingSenderId: '161385731577',
    projectId: 'huong-nghiep',
    storageBucket: 'huong-nghiep.appspot.com',
    iosClientId:
        '161385731577-ugoegbmp47386rmhena4pfoieqi0r020.apps.googleusercontent.com',
    iosBundleId: 'com.example.huongNghiep',
  );
}
